# Generated by Django 4.2.4 on 2023-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='Is student'),
        ),
    ]
