# Generated by Django 4.2.4 on 2024-01-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('instructor_image', models.ImageField(upload_to='Images/Instructors')),
                ('instructor_bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
