# Generated by Django 4.2.4 on 2024-01-07 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_instructor_delete_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_limit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_updated_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='promotional_video',
        ),
        migrations.RemoveField(
            model_name='course',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='skills_taught',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='course',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_students_enrolled',
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='Images/Featured_Image/featured_img'),
        ),
        migrations.AddField(
            model_name='course',
            name='featured_video',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.categories'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
