# Generated by Django 4.2.4 on 2024-01-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0007_remove_course_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='Is instructor'),
        ),
    ]
