# Generated by Django 4.2.4 on 2024-01-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0008_instructor_is_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='is_instructor',
        ),
    ]
