# Generated by Django 4.2.4 on 2024-01-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0010_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_image',
            new_name='instructor_cover',
        ),
    ]
