# Generated by Django 4.2.4 on 2024-01-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0014_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='user_bio',
            field=models.TextField(default=False),
        ),
    ]
