# Generated by Django 4.2.4 on 2024-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0015_remove_user_bio_user_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.TextField(default=' '),
        ),
    ]
