# Generated by Django 4.2.4 on 2024-01-08 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0019_alter_user_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
