# Generated by Django 4.2.4 on 2024-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0022_alter_user_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/profile'),
        ),
    ]
