# Generated by Django 4.2.4 on 2024-01-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0024_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured_video',
        ),
    ]
