# Generated by Django 4.2.4 on 2024-01-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0027_alter_blog_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
