# Generated by Django 4.2.4 on 2024-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0030_delete_payment_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT'), ('PENDING', 'PENDING')], max_length=100, null=True),
        ),
    ]
