# Generated by Django 4.2.4 on 2024-01-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0034_course_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
