# Generated by Django 4.2.4 on 2024-01-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0035_alter_course_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pending',
        ),
    ]
