# Generated by Django 4.2.4 on 2024-01-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0036_remove_course_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
