# Generated by Django 4.2.4 on 2024-01-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0042_user_not_is_verified_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='not_is_verified_instructor',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('STUDENT', 'STUDNET'), ('PENDING', 'PENDING')], default='STUDENT', max_length=100, null=True),
        ),
    ]
