# Generated by Django 4.2.4 on 2024-01-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0043_remove_user_not_is_verified_instructor_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified_instructor',
        ),
    ]
