# Generated by Django 4.2.4 on 2024-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0044_remove_user_is_verified_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('STUDENT', 'STUDNET'), ('PENDING', 'PENDING'), ('INSTRUCTOR', 'INSTRUCTOR')], default='STUDENT', max_length=100, null=True),
        ),
    ]
