# Generated by Django 4.2.4 on 2024-01-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0045_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_nember', models.IntegerField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='Media/Lesson')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=200)),
                ('time_duration', models.FloatField(null=True)),
                ('preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.lesson')),
            ],
        ),
    ]
