# Generated by Django 4.2.4 on 2024-01-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0046_lesson_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='serial_nember',
            new_name='serial_number',
        ),
    ]
