# Generated by Django 4.2.4 on 2024-01-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0048_alter_video_thumbnail_digitalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='mobile',
            field=models.CharField(default='980000000', max_length=15),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='widget_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
