# Generated by Django 4.2.4 on 2024-01-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0049_digitalproduct_mobile_digitalproduct_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproduct',
            name='token',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='widget_id',
        ),
    ]
