# Generated by Django 4.2.4 on 2024-01-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0052_message_delete_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproduct',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
