# Generated by Django 4.2.4 on 2024-01-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0055_alter_digitalproduct_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.course'),
        ),
    ]
