# Generated by Django 4.2.4 on 2024-01-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0056_digitalproduct_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproduct',
            name='course_id',
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='product_identity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
