# Generated by Django 4.2.4 on 2024-01-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0057_remove_digitalproduct_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.course'),
        ),
    ]
