# Generated by Django 4.2.4 on 2024-01-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0060_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
